-- Create crash data tables
CREATE TABLE crash_data (
  objectid INT PRIMARY KEY,
  accident_no VARCHAR(30),
  accident_date DATE,
  accident_time VARCHAR(30),
  accident_type VARCHAR(100),
  road_geometry VARCHAR(100),
  severity VARCHAR(100),
  speed_zone VARCHAR(100),
  node_id INT,
  longitude FLOAT,
  latitude FLOAT,
  suburb TEXT,
  postcode INT,
  node_type VARCHAR(100),
  lga_name TEXT,
  region_name TEXT,
  total_persons INT,
  inj_or_fatal INT,
  fatality INT,
  seriousinjury INT,
  otherinjury INT,
  noninjured INT,
  males INT,
  females INT,
  bicyclist INT,
  passenger INT,
  driver INT,
  pedestrian INT,
  pillion INT,
  motorist INT,
  old_pedestrian INT,
  old_driver INT,
  young_driver INT,
  alcohol_related TEXT,
  no_of_vehicles INT,
  heavyvehicle INT,
  passengervehicle INT,
  motorcycle INT,
  publicvehicle INT
);